name: step_tracker
description: A new Flutter Task.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.5.0
  firebase_auth:
  firebase_core: ^1.24.0
  #pedo meter
  pedometer: ^3.0.0
    # Bloc for state management
  flutter_bloc: ^8.0.1
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.3
  # Service locator
  get_it: ^7.2.0
  # Remote API
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.4
  # Local cache
  shared_preferences: 2.0.11
  #screen responsive
  flutter_screenutil:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

